<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Inboundsys-Mac-Dhanalakshmi.local" ignored="0" name="homepage" tests="5" failures="3" timestamp="29 Oct 2018 12:02:30 GMT" time="75.14" errors="0">
  <testcase name="verifyloggedusername" time="6.847" classname="com.hubspotcrm.Testcases.HomePageTest"/>
  <testcase name="verifylogourlTest" time="10.838" classname="com.hubspotcrm.Testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [https://app.hubspot.com/reports-dashboard/5068902/sales] but found [https://app.hubspot.com/reports-dashboard/5068902/view]">
      <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/reports-dashboard/5068902/sales] but found [https://app.hubspot.com/reports-dashboard/5068902/view]
at com.hubspotcrm.Testcases.HomePageTest.verifylogourlTest(HomePageTest.java:44)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifylogourlTest -->
  <testcase name="verifycontacturlTest" time="8.134" classname="com.hubspotcrm.Testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]">
      <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]
at com.hubspotcrm.Testcases.HomePageTest.verifycontacturlTest(HomePageTest.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifycontacturlTest -->
  <testcase name="verifycompaniesurlTest" time="12.038" classname="com.hubspotcrm.Testcases.HomePageTest"/>
  <testcase name="verifyactivityurlTest" time="7.726" classname="com.hubspotcrm.Testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [https://app.hubspot.com/activity-feed/5068902/view] but found [https://app.hubspot.com/activity-feed/5068902]">
      <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/activity-feed/5068902/view] but found [https://app.hubspot.com/activity-feed/5068902]
at com.hubspotcrm.Testcases.HomePageTest.verifyactivityurlTest(HomePageTest.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyactivityurlTest -->
</testsuite> <!-- homepage -->
