<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="HubspotCrm" duration-ms="106204" started-at="2018-10-29T12:00:38Z" finished-at="2018-10-29T12:02:24Z">
    <groups>
    </groups>
    <test name="loginpage" duration-ms="25949" started-at="2018-10-29T12:00:38Z" finished-at="2018-10-29T12:01:04Z">
      <class name="com.hubspotcrm.Testcases.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="setup" is-config="true" duration-ms="8109" started-at="2018-10-29T12:00:38Z" finished-at="2018-10-29T12:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginverifyTest()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="loginverifyTest" duration-ms="1056" started-at="2018-10-29T12:00:46Z" finished-at="2018-10-29T12:00:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginverifyTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="teardown" is-config="true" duration-ms="103" started-at="2018-10-29T12:00:47Z" finished-at="2018-10-29T12:00:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="setup" is-config="true" duration-ms="3809" started-at="2018-10-29T12:00:48Z" finished-at="2018-10-29T12:00:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyPasswordTest()[pri:2, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="verifyPasswordTest" duration-ms="625" started-at="2018-10-29T12:00:51Z" finished-at="2018-10-29T12:00:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPasswordTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="teardown" is-config="true" duration-ms="82" started-at="2018-10-29T12:00:52Z" finished-at="2018-10-29T12:00:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="setup" is-config="true" duration-ms="4797" started-at="2018-10-29T12:00:52Z" finished-at="2018-10-29T12:00:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLinksTest()[pri:3, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="verifyLinksTest" duration-ms="402" started-at="2018-10-29T12:00:57Z" finished-at="2018-10-29T12:00:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.hubspotcrm.Testcases.LoginPageTest.verifyLinksTest(LoginPageTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinksTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="teardown" is-config="true" duration-ms="120" started-at="2018-10-29T12:00:57Z" finished-at="2018-10-29T12:00:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="setup" is-config="true" duration-ms="4889" started-at="2018-10-29T12:00:57Z" finished-at="2018-10-29T12:01:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyErrormessageTest()[pri:4, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="verifyErrormessageTest" duration-ms="1756" started-at="2018-10-29T12:01:02Z" finished-at="2018-10-29T12:01:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyErrormessageTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.hubspotcrm.Testcases.LoginPageTest@31ef45e3]" name="teardown" is-config="true" duration-ms="104" started-at="2018-10-29T12:01:04Z" finished-at="2018-10-29T12:01:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.hubspotcrm.Testcases.LoginPageTest -->
    </test> <!-- loginpage -->
    <test name="homepage" duration-ms="75140" started-at="2018-10-29T12:01:09Z" finished-at="2018-10-29T12:02:24Z">
      <class name="com.hubspotcrm.Testcases.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="setup" is-config="true" duration-ms="6052" started-at="2018-10-29T12:01:09Z" finished-at="2018-10-29T12:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyloggedusername()[pri:1, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="verifyloggedusername" duration-ms="6847" started-at="2018-10-29T12:01:15Z" finished-at="2018-10-29T12:01:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloggedusername -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="tearDown" is-config="true" duration-ms="113" started-at="2018-10-29T12:01:22Z" finished-at="2018-10-29T12:01:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="setup" is-config="true" duration-ms="5004" started-at="2018-10-29T12:01:22Z" finished-at="2018-10-29T12:01:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifylogourlTest()[pri:2, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="verifylogourlTest" duration-ms="10838" started-at="2018-10-29T12:01:27Z" finished-at="2018-10-29T12:01:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://app.hubspot.com/reports-dashboard/5068902/sales] but found [https://app.hubspot.com/reports-dashboard/5068902/view]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/reports-dashboard/5068902/sales] but found [https://app.hubspot.com/reports-dashboard/5068902/view]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hubspotcrm.Testcases.HomePageTest.verifylogourlTest(HomePageTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifylogourlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="tearDown" is-config="true" duration-ms="197" started-at="2018-10-29T12:01:38Z" finished-at="2018-10-29T12:01:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="setup" is-config="true" duration-ms="5072" started-at="2018-10-29T12:01:38Z" finished-at="2018-10-29T12:01:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifycontacturlTest()[pri:3, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="verifycontacturlTest" duration-ms="8134" started-at="2018-10-29T12:01:43Z" finished-at="2018-10-29T12:01:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/contacts/5068902/contacts/list/view/all/?] but found [https://app.hubspot.com/contacts/5068902/contacts]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hubspotcrm.Testcases.HomePageTest.verifycontacturlTest(HomePageTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycontacturlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="tearDown" is-config="true" duration-ms="84" started-at="2018-10-29T12:01:52Z" finished-at="2018-10-29T12:01:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="setup" is-config="true" duration-ms="6728" started-at="2018-10-29T12:01:52Z" finished-at="2018-10-29T12:01:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifycompaniesurlTest()[pri:4, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="verifycompaniesurlTest" duration-ms="12038" started-at="2018-10-29T12:01:58Z" finished-at="2018-10-29T12:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycompaniesurlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="tearDown" is-config="true" duration-ms="206" started-at="2018-10-29T12:02:10Z" finished-at="2018-10-29T12:02:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="setup" is-config="true" duration-ms="5856" started-at="2018-10-29T12:02:11Z" finished-at="2018-10-29T12:02:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyactivityurlTest()[pri:5, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="verifyactivityurlTest" duration-ms="7726" started-at="2018-10-29T12:02:17Z" finished-at="2018-10-29T12:02:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://app.hubspot.com/activity-feed/5068902/view] but found [https://app.hubspot.com/activity-feed/5068902]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://app.hubspot.com/activity-feed/5068902/view] but found [https://app.hubspot.com/activity-feed/5068902]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hubspotcrm.Testcases.HomePageTest.verifyactivityurlTest(HomePageTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyactivityurlTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspotcrm.Testcases.HomePageTest@4b952a2d]" name="tearDown" is-config="true" duration-ms="154" started-at="2018-10-29T12:02:24Z" finished-at="2018-10-29T12:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hubspotcrm.Testcases.HomePageTest -->
    </test> <!-- homepage -->
  </suite> <!-- HubspotCrm -->
</testng-results>
